Repository gaidds/React-crm-project, pull requests merged in 2024-11, with the labels that each got.

#69 I1BCIP-135: Total net income
  src/pages/dashboard/Dashboard.tsx
Labels: ready to merge

#71 I1BCIP-157: create pagination component
  src/components/pagination/Pagination.tsx
  src/components/pagination/styled.tsx
  src/components/pagination/types.ts
  src/pages/accounts/Accounts.tsx
  src/pages/contacts/Contacts.tsx
  src/pages/deals/Deals.tsx
  src/pages/users/Users.tsx
Labels: under test and review

#73 I1BCIP-137: Created dashboard deals ratio card
  src/pages/dashboard/Dashboard.tsx
Labels: under test and review

#74 I1BCIP-144: deals countries map
  package-lock.json
  package.json
  src/pages/dashboard/Dashboard.tsx
  src/pages/dashboard/MapDashboard.tsx
  src/pages/dashboard/country-coordinates.ts
  src/pages/dashboard/styles.css
  src/pages/dashboard/types.ts
Labels: under test and review

#75 I1BCIP 140 deal sources bar chart
  src/pages/dashboard/Dashboard.tsx
  src/pages/dashboard/DealSourcesBarChart.tsx
  src/pages/dashboard/styles.css
Labels: Not ready

#76 I1BCIP-142: create top 5 deals table
  src/components/dashboard-card/styles.css
  src/pages/dashboard/Dashboard.tsx
  src/pages/dashboard/TopDealsTable.tsx
  src/pages/dashboard/styles.css
  src/pages/dashboard/types.ts
Labels: under test and review

#78 I1BCIP-142: Add euro sign to the deal value of top deals table
  src/pages/dashboard/TopDealsTable.tsx
Labels: under test and review

#77 I1BCIP-168: Fixed the key warning of stages bar component
  src/components/stages-bar/StagesBar.tsx
Labels: under test and review
